#include "ake_drone_sim/astar3d.hpp"
#include "ake_drone_sim/bspline.hpp"
#include "ake_drone_sim/mpc_smoother.hpp"
#include "ake_drone_sim/pointcloud_utils.hpp"
#include "drone_msgs/msg/trajectory_setpoint.hpp"
#include <rclcpp/rclcpp.hpp>
#include <nav_msgs/msg/odometry.hpp>
#include <nav_msgs/msg/path.hpp>
#include <geometry_msgs/msg/pose_stamped.hpp>
#include <std_msgs/msg/string.hpp>
#include <deque>
#include <unordered_set>

using namespace std::chrono_literals;
namespace ake_drone_sim {
class PlannerNode final:public rclcpp::Node{
 public:PlannerNode():Node("ab_planner_node"),astar_(declare_parameter("max_search_nodes",250000),declare_parameter("heuristic_weight",1.05)),mpc_(){
  resolution_=declare_parameter("resolution",0.2);safety_=declare_parameter("safety_distance",0.5)+declare_parameter("vehicle_radius",0.18);speed_=declare_parameter("reference_speed",1.2);cruise_=declare_parameter("cruise_altitude",1.5);lidar_timeout_=declare_parameter("lidar_timeout",2.0);
  grid_.configure({-2,-4,0},{12,8,5},resolution_);auto qos=rclcpp::QoS(1).transient_local().reliable();
  map_sub_=create_subscription<sensor_msgs::msg::PointCloud2>("/map/obstacles",qos,std::bind(&PlannerNode::mapCb,this,std::placeholders::_1));
  lidar_sub_=create_subscription<sensor_msgs::msg::PointCloud2>("/drone/lidar/points",rclcpp::SensorDataQoS(),std::bind(&PlannerNode::lidarCb,this,std::placeholders::_1));
  odom_sub_=create_subscription<nav_msgs::msg::Odometry>("/drone/odom",10,std::bind(&PlannerNode::odomCb,this,std::placeholders::_1));
  goal_sub_=create_subscription<geometry_msgs::msg::PoseStamped>("/drone/goal",10,std::bind(&PlannerNode::goalCb,this,std::placeholders::_1));
  ref_pub_=create_publisher<drone_msgs::msg::TrajectorySetpoint>("/drone/reference",10);safe_pub_=create_publisher<geometry_msgs::msg::PoseStamped>("/drone/safe_goal",10);planned_pub_=create_publisher<nav_msgs::msg::Path>("/drone/planned_path",qos);spline_pub_=create_publisher<nav_msgs::msg::Path>("/drone/bspline_path",qos);mpc_pub_=create_publisher<nav_msgs::msg::Path>("/drone/mpc_prediction_path",10);status_pub_=create_publisher<std_msgs::msg::String>("/drone/planner_status",10);
  goal_={0,0,cruise_};have_goal_=declare_parameter("auto_takeoff",true);timer_=create_wall_timer(20ms,std::bind(&PlannerNode::tick,this));}
 private:
  void mapCb(const sensor_msgs::msg::PointCloud2::SharedPtr m){const bool first_map=!have_map_;grid_.clear();for(const auto&p:readCloud(*m))grid_.set(grid_.worldToGrid(p));inflated_=grid_.inflated(safety_);have_map_=true;if(first_map)need_plan_=true;}
  void odomCb(const nav_msgs::msg::Odometry::SharedPtr m){position_=eigen(m->pose.pose.position);velocity_=eigen(m->twist.twist.linear);orientation_=eigen(m->pose.pose.orientation).normalized();if(!have_odom_)takeoff_xy_=position_.head<2>();have_odom_=true;}
  void goalCb(const geometry_msgs::msg::PoseStamped::SharedPtr m){Eigen::Vector3d new_goal=eigen(m->pose.position);if(new_goal.z()<0.2)new_goal.z()=cruise_;if(have_goal_&&(new_goal-goal_).norm()<1e-4)return;goal_=new_goal;Eigen::Quaterniond q=eigen(m->pose.orientation);goal_yaw_=std::atan2(2*(q.w()*q.z()+q.x()*q.y()),1-2*(q.y()*q.y()+q.z()*q.z()));have_goal_=true;need_plan_=true;lidar_replan_count_=0;}
  void lidarCb(const sensor_msgs::msg::PointCloud2::SharedPtr m){std::vector<Eigen::Vector3d>frame;for(const auto&p:readCloud(*m))frame.push_back(position_+orientation_*p);lidar_history_.push_back(std::move(frame));while(lidar_history_.size()>3)lidar_history_.pop_front();last_lidar_=now();have_lidar_=true;
    if(spline_.valid()&&!use_polyline_){int hits=0;for(const auto&f:lidar_history_)for(const auto&o:f)for(double u=current_u_;u<=std::min(spline_.maxU(),current_u_+2.0);u+=0.08)if((spline_.position(u)-o).norm()<0.18){++hits;break;}if(hits>0){if(++threat_hits_>=5&&lidar_replan_count_==0){need_plan_=true;++lidar_replan_count_;}}else threat_hits_=0;}}
  bool splineSafe(const BSpline&s)const{for(double u=0;u<=s.maxU();u+=0.03)if(inflated_.occupiedWorld(s.position(u)))return false;return true;}
  void publishPath(const std::vector<Eigen::Vector3d>&points,const rclcpp::Publisher<nav_msgs::msg::Path>::SharedPtr&pub){nav_msgs::msg::Path p;p.header.stamp=now();p.header.frame_id="map";for(const auto&v:points){geometry_msgs::msg::PoseStamped ps;ps.header=p.header;ps.pose.position=pointMsg(v);ps.pose.orientation.w=1;p.poses.push_back(ps);}pub->publish(p);}
  void plan(){need_plan_=false;auto result=astar_.plan(inflated_,position_,goal_);if(!result.success){path_ready_=false;status("PLAN_FAILED:"+result.reason);return;}path_=result.path;publishPath(path_,planned_pub_);
    use_polyline_=false;auto controls=makeSplineControlPoints(path_,0.55);BSpline candidate;candidate.setControlPoints(controls,0.7);if(candidate.valid()&&splineSafe(candidate)){spline_=candidate;}else{auto dense=path_;if(dense.size()<2){path_ready_=false;return;}controls=makeSplineControlPoints(dense,0.1);candidate.setControlPoints(controls,0.25);if(!splineSafe(candidate)){use_polyline_=true;path_ready_=true;publishPath(path_,spline_pub_);status("EXECUTING_ASTAR_FALLBACK expanded="+std::to_string(result.expanded));return;}spline_=candidate;}
    table_.build(spline_);current_u_=0;path_ready_=true;std::vector<Eigen::Vector3d>samples;for(double u=0;u<=spline_.maxU();u+=0.03)samples.push_back(spline_.position(u));publishPath(samples,spline_pub_);status("EXECUTING expanded="+std::to_string(result.expanded));}
  void hold(){publishReference({position_.x(),position_.y(),std::max(position_.z(),0.05)},Eigen::Vector3d::Zero(),Eigen::Vector3d::Zero(),goal_yaw_);}
  void publishReference(const Eigen::Vector3d&p,const Eigen::Vector3d&v,const Eigen::Vector3d&a,double yaw){drone_msgs::msg::TrajectorySetpoint m;m.header.stamp=now();m.header.frame_id="map";m.position=pointMsg(p);m.velocity=vectorMsg(v);m.acceleration=vectorMsg(a);m.yaw=yaw;ref_pub_->publish(m);geometry_msgs::msg::PoseStamped s;s.header=m.header;s.pose.position=m.position;s.pose.orientation=quatMsg(quaternionFromYaw(yaw));safe_pub_->publish(s);}
  void tick(){if(!have_odom_)return;if(position_.z()<cruise_-0.25){publishReference({takeoff_xy_.x(),takeoff_xy_.y(),cruise_},Eigen::Vector3d::Zero(),Eigen::Vector3d::Zero(),goal_yaw_);return;}if(!have_map_||!have_goal_){hold();return;}if(have_lidar_&&(now()-last_lidar_).seconds()>lidar_timeout_){status("LIDAR_TIMEOUT_HOLD");hold();return;}if(need_plan_)plan();if(!path_ready_){hold();return;}if(use_polyline_){Eigen::Vector3d target=goal_;double best=1e100;size_t best_segment=0;double best_t=0;for(size_t i=0;i+1<path_.size();++i){Eigen::Vector3d d=path_[i+1]-path_[i];double t=clamp((position_-path_[i]).dot(d)/std::max(1e-9,d.squaredNorm()),0.0,1.0);double e=(position_-(path_[i]+t*d)).squaredNorm();if(e<best){best=e;best_segment=i;best_t=t;}}double remain=.8;target=path_[best_segment]+best_t*(path_[best_segment+1]-path_[best_segment]);for(size_t i=best_segment;i+1<path_.size()&&remain>0;++i){Eigen::Vector3d end=path_[i+1];double length=(end-target).norm();if(length>=remain){target+=(end-target).normalized()*remain;remain=0;}else{remain-=length;target=end;}}Eigen::Vector3d delta=target-position_;Eigen::Vector3d vel=Eigen::Vector3d::Zero();if(delta.norm()>0.1)vel=delta.normalized()*std::min(speed_,delta.norm());publishReference(target,vel,Eigen::Vector3d::Zero(),goal_yaw_);if((position_-goal_).norm()<.2&&velocity_.norm()<.25)status("GOAL_REACHED");return;}
    current_u_=table_.closestU(spline_,position_,current_u_);double du=speed_*0.02/std::max(0.2,spline_.velocity(current_u_).norm());double command_u=std::min(spline_.maxU(),current_u_+du);
    std::vector<KinematicState>refs;for(int k=0;k<30;++k){double u=std::min(spline_.maxU(),command_u+0.04*k);refs.push_back({spline_.position(u),spline_.velocity(u),spline_.acceleration(u)});}KinematicState initial{position_,velocity_,Eigen::Vector3d::Zero()};auto prediction=mpc_.solve(initial,refs);if(prediction.empty()){status("MPC_FAILED_HOLD");hold();return;}
    bool safe=true;for(const auto&x:prediction)if(inflated_.occupiedWorld(x.p)){safe=false;break;}const size_t command_index=std::min<size_t>(15,prediction.size()-1);const auto&cmd=safe?prediction[command_index]:refs.front();publishReference(cmd.p,cmd.v,cmd.a,goal_yaw_);std::vector<Eigen::Vector3d>pp;for(const auto&x:prediction)pp.push_back(x.p);publishPath(pp,mpc_pub_);if((position_-goal_).norm()<0.2&&velocity_.norm()<0.25)status("GOAL_REACHED");}
  void status(const std::string&s){if(s==last_status_)return;last_status_=s;std_msgs::msg::String m;m.data=s;status_pub_->publish(m);RCLCPP_INFO(get_logger(),"%s",s.c_str());}
  VoxelGrid grid_,inflated_;AStar3D astar_;MpcSmoother mpc_;BSpline spline_;ArcLengthTable table_;std::vector<Eigen::Vector3d>path_;std::deque<std::vector<Eigen::Vector3d>>lidar_history_;Eigen::Vector3d position_,velocity_,goal_;Eigen::Vector2d takeoff_xy_{Eigen::Vector2d::Zero()};Eigen::Quaterniond orientation_{Eigen::Quaterniond::Identity()};double resolution_,safety_,speed_,cruise_,lidar_timeout_,goal_yaw_{0},current_u_{0};bool have_map_{false},have_odom_{false},have_goal_{false},have_lidar_{false},need_plan_{true},path_ready_{false},use_polyline_{false};int threat_hits_{0},lidar_replan_count_{0};rclcpp::Time last_lidar_{0,0,RCL_ROS_TIME};std::string last_status_;
  rclcpp::Subscription<sensor_msgs::msg::PointCloud2>::SharedPtr map_sub_,lidar_sub_;rclcpp::Subscription<nav_msgs::msg::Odometry>::SharedPtr odom_sub_;rclcpp::Subscription<geometry_msgs::msg::PoseStamped>::SharedPtr goal_sub_;rclcpp::Publisher<drone_msgs::msg::TrajectorySetpoint>::SharedPtr ref_pub_;rclcpp::Publisher<geometry_msgs::msg::PoseStamped>::SharedPtr safe_pub_;rclcpp::Publisher<nav_msgs::msg::Path>::SharedPtr planned_pub_,spline_pub_,mpc_pub_;rclcpp::Publisher<std_msgs::msg::String>::SharedPtr status_pub_;rclcpp::TimerBase::SharedPtr timer_;
};}
int main(int argc,char**argv){rclcpp::init(argc,argv);rclcpp::spin(std::make_shared<ake_drone_sim::PlannerNode>());rclcpp::shutdown();}
